// <auto-generated />
using System;
using AccountsApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AccountsApi.Migrations
{
    [DbContext(typeof(AccountContext))]
    partial class AccountContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AccountsApi.Models.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("Birth")
                        .HasColumnName("birth");

                    b.Property<string>("City")
                        .HasColumnName("city")
                        .HasMaxLength(50);

                    b.Property<string>("Country")
                        .HasColumnName("country")
                        .HasMaxLength(50);

                    b.Property<string>("EMail")
                        .HasColumnName("email")
                        .HasMaxLength(100);

                    b.Property<string>("FName")
                        .HasColumnName("fname")
                        .HasMaxLength(50);

                    b.Property<string[]>("Interests")
                        .HasColumnName("interests");

                    b.Property<DateTime>("Joined")
                        .HasColumnName("joined");

                    b.Property<long[]>("LikeIds")
                        .HasColumnName("like_ids");

                    b.Property<long[]>("LikeTSs")
                        .HasColumnName("like_tss");

                    b.Property<string>("Phone")
                        .HasColumnName("phone")
                        .HasMaxLength(16);

                    b.Property<long?>("PremiumFinish")
                        .HasColumnName("premium_finish");

                    b.Property<long?>("PremiumStart")
                        .HasColumnName("premium_start");

                    b.Property<string>("SName")
                        .HasColumnName("sname")
                        .HasMaxLength(50);

                    b.Property<int>("Sex")
                        .HasColumnName("sex");

                    b.Property<string>("Status")
                        .HasColumnName("status")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
